#!/bin/bash
cd /home/ecospec
umask 002
while [ '1' -eq '1' ]
do
echo "Starting EcoSpec at " `date` >> /var/log/ecospecd.log
python ecospec.py
set EXITVALUE=$?
echo "ecospec.py exit value: $EXITVALUE"
echo "Stopping EcoSpec at " `date` >> /var/log/ecospecd.log
if [ "$EXITVALUE " != "0 " ]; then
    sleep 10
fi
done
