#!/bin/bash
echo Is checker.py running?
ps -Al | grep checker || echo "No."

echo Is ecospec.py running?
ps -Al | grep ecospec || echo "No."

echo Is PPP running?
ps -Al | grep pppd || echo "No."

echo Is wvdial running?
ps -Al | grep wvdial || echo "No."

echo Is mover.py running?
ps -Al | grep mover || echo "No."

echo 'Can we ping localhost?'
ping -c 1 -W 3 -v localhost || echo "No."

echo 'Can we ping the RPi IP address (146.137.13.115)?'
ping -c 1 -W 3 -v 146.137.13.115 || echo "No."

echo 'Can we ping the Fieldspec4 address (146.137.13.117)?'
ping -c 1 -W 3 -v 146.137.13.117 || echo "No."

echo 'Can we ping the Data Logger address (146.137.13.118)?'
ping -c 1 -W 3 -v 146.137.13.118 || echo "No."

echo 'Can we ping the Camera address (146.137.13.119)?'
ping -c 1 -W 3 -v 146.137.13.119 || echo "No."

arp -a
