#!/bin/bash

wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/axis-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/axis_q1604.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/checker.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/cr1000-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/cr1000.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/ecospec.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.checker
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.ecospec
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.wvdial
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.network.interfaces
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.wvdial.conf
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fieldspec4.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try2.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try3.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try4.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/ptu-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/ptu_d300.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/status
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/update

chmod 666 *
chmod 775 checker.py
chmod 775 ecospec.py
chmod 775 status
chmod 775 update
chmod 775 update_ecospec

cp etc.network.interfaces /etc/network/interfaces && chmod 666 /etc/network/interfaces
cp etc.wvdial.conf        /etc/wvdial.conf        && chmod 666 /etc/wvdial.conf
cp etc.init.d.checker     /etc/init.d/checker     && chmod 775 /etc/init.d/checker
cp etc.init.d.ecospec     /etc/init.d/ecospec     && chmod 775 /etc/init.d/ecospec
cp etc.init.d.wvdial      /etc/init.d/wvdial      && chmod 775 /etc/init.d/wvdial

update-rc.d wvdial  defaults 95
update-rc.d ecospec defaults 96
update-rc.d checker defaults 97

echo all updated!
