#!/bin/bash

mkdir     /var/log/checker
chmod 777 /var/log/checker    
mkdir     /var/log/ecospec
chmod 777 /var/log/ecospec 
mkdir     /var/log/mover
chmod 777 /var/log/mover

mkdir     poster
chown pi  poster
chmod 777 poster

wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/axis-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/axis_q1604.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/checker.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/cr1000-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/cr1000.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/ecospec.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.checker
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.ecospec
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.mover
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.init.d.wvdial
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.network.interfaces
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/etc.wvdial.conf
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/extend_white_reference_arm.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fieldspec4.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try2.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try3.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/fs4-try4.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/mover.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/piface.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/power_down.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/power_up.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/ptu-try1.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/ptu_d300.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/retract_white_reference_arm.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/status
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/update
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/update_ecospec
cd poster
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/poster/streaminghttp.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/poster/encode.py
wget -N https://raw.githubusercontent.com/donaldbales/ecospec/master/poster/__init__.py
cd ..

chown pi *
chmod 666 *

chmod 775 extend_white_reference_arm.py
chmod 775 power_up.py
chmod 775 power_down.py
chmod 775 ecospec.py
chmod 775 checker.py
chmod 775 retract_white_reference_arm.py
chmod 775 mover.py
chmod 775 status
chmod 775 update
chmod 775 update_ecospec

cp etc.network.interfaces /etc/network/interfaces && chmod 666 /etc/network/interfaces
cp etc.wvdial.conf        /etc/wvdial.conf        && chmod 666 /etc/wvdial.conf
cp etc.init.d.checker     /etc/init.d/checker     && chmod 775 /etc/init.d/checker
cp etc.init.d.ecospec     /etc/init.d/ecospec     && chmod 775 /etc/init.d/ecospec
cp etc.init.d.mover       /etc/init.d/mover       && chmod 775 /etc/init.d/mover
cp etc.init.d.wvdial      /etc/init.d/wvdial      && chmod 775 /etc/init.d/wvdial

update-rc.d wvdial  defaults 95
update-rc.d ecospec defaults 96
update-rc.d checker defaults 97
update-rc.d mover   defaults 98

echo all updated!
